[package]
name = "htmldiff"
version = "0.1.0"
authors = ["Seiichi KONDO <kondo.seikichi@gmail.com>"]
description = """
htmldiff is a Rust port of https://github.com/myobie/htmldiff
"""
documentation = "https://github.com/seikichi/htmldiff"
homepage = "https://github.com/seikichi/htmldiff"
repository = "https://github.com/seikichi/htmldiff"
readme = "README.md"
keywords = ["html", "diff"]
license = "MIT"
edition = "2021"

[dependencies]
kuchiki = "0.8.1"
rand = "0.10.0"
unicode-segmentation = "1.13.2"

[dev-dependencies]
proptest = "1.11.0"
rand = "0.10.0" # reuse same version
kuchiki = "0.8.1"
